import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import ClientWrapper from "@/components/ClientWrapper";
import Header from "@/components/Header";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body
        className={`bg-zinc-900`}
      >
        <ClerkProvider> {/* <-- Add this wrapper */}
          <ClientWrapper>
            <Header />
            <main>{children}</main>
            {/* <Toaster position="bottom-center" /> */}
          </ClientWrapper>
        </ClerkProvider>
      </body>
    </html>
  );
}
