import type { Metadata } from "next";

import "./globals.css";
import ClientWrapper from "@/components/ClientWrapper";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-gradient-to-br from-zinc-900 via-zinc-900 to-zinc-800`}
      >
      <ClientWrapper>
        <Header/>
        <main>{children}</main>
        
        </ClientWrapper>
      </body>
    </html>
  );
}
